### ISSUE TITLE
Web generator does not work

### ISSUE THREAD

**Issue by xavier-gl71** [pongasoft/jamba#7] opened 2019-07-26 17:15 UTC
Hello

No generated file.
Tested with Firefox and Edge (Windows 10 x64)

With Firefox:
```
### Jamba Plugin Generator Output ###
[OK] Ready.
Wating for user input...
Loading Jamba Blank Plugin...
Loaded Jamba Blank Plugin version v3.2.2 - 36 files.
Plugin [testplugin-src.zip] generated successfully. Downloading...
Download complete (check you download folder).
```

With Edge:
```
### Jamba Plugin Generator Output ###
[OK] Ready.
Wating for user input...
Loading Jamba Blank Plugin...
Loaded Jamba Blank Plugin version v3.2.2 - 36 files.
Could not fetch blank plugin - Object doesn't support property or method 'keys'. Try refreshing the page...
```

Any idea? Thanks.

**Comment by ypujante** [comment] 2019-07-26 17:18
The output shows that you are getting a result with Firefox:

```
Plugin [testplugin-src.zip] generated successfully. Downloading...
Download complete (check you download folder).
```

Can you please confirm that you can see the plugin with Firefox?

It seems that it does not work with Edge but I have not tested it with Edge.. I will take a look at it but Firefox seems to be good.

**Comment by xavier-gl71** [comment] 2019-07-26 17:27
I did check the download folder. No file.
There is actually no 'testplugin*' file on my hard drive.

**Comment by ypujante** [comment] 2019-07-26 17:32
Ok. I will take a look. I am pretty sure it works with Chrome so you may want to try with Chrome

**Comment by xavier-gl71** [comment] 2019-07-26 17:38
No hurry. If there's no quick fix I'll try the command line tool.

**Comment by ypujante** [comment] 2019-07-26 17:49
Ok. I am just bummed cause that is one of the main point of the website...

**Comment by ypujante** [comment] 2019-07-26 20:49
I believe the issue is fixed if you can confirm. I tried with Firefox and Edge from a Win10 machine with no issue now. I also added a Download link in case the download does not happen automatically.

**Comment by xavier-gl71** [comment] 2019-07-27 08:31
Hi

Nice! I can get the file with Firefox.

But I still get the same error message with Edge  : 
`Could not fetch blank plugin - Object doesn't support property or method 'keys'. Try refreshing the page...`
I did refresh the page and  clear the cache and cookies... I'll try again later.

**Comment by ypujante** [comment] 2019-07-27 15:43
Glad to hear it is working with Firefox.

I am a bit puzzled with Edge because I cannot reproduce the problem. I am using Edge v44.18362.1.0 which I believe is the most recent version and it just works.

The only time when I use the `keys` method is with the `FormData` object which according to the [spec](https://developer.mozilla.org/en-US/docs/Web/API/FormData/keys) is compatible with Edge...

**Comment by xavier-gl71** [comment] 2019-07-27 15:58
I have an older version (v42.17…) that might be not compatible. 
I suppose you can close the issue.

Thanks for this project.

**Comment by ypujante** [comment] 2019-07-27 16:00
Closing this issue since one issue has been fixed and the other one is most likely due to an older version.

**Closed by ypujante** 2019-07-27 16:00 UTC
Labels: bug, jamba.dev
